package agentspinner

// Predefined spinner names.
const (
	// Classic spinners
	Braille      Name = "braille"
	BrailleWave  Name = "braillewave"
	DNA          Name = "dna"
	Scan         Name = "scan"
	Rain         Name = "rain"
	ScanLine     Name = "scanline"
	Pulse        Name = "pulse"
	Snake        Name = "snake"
	Sparkle      Name = "sparkle"
	Cascade      Name = "cascade"
	Columns      Name = "columns"
	Orbit        Name = "orbit"
	Breathe      Name = "breathe"
	WaveRows     Name = "waverows"
	Checkerboard Name = "checkerboard"
	Helix        Name = "helix"
	FillSweep    Name = "fillsweep"
	DiagSwipe    Name = "diagswipe"

	// Modern spinners
	Dots         Name = "dots"
	Bounce       Name = "bounce"
	Ripple       Name = "ripple"
	Bars         Name = "bars"
	Radar        Name = "radar"
	Typing       Name = "typing"
	Loading      Name = "loading"
	PingPong     Name = "pingpong"
	Star         Name = "star"
	Arrow        Name = "arrow"
	Wave         Name = "wave"
	Progress     Name = "progress"
	Circle       Name = "circle"
	Cross        Name = "cross"
	Zigzag       Name = "zigzag"
	Diamond      Name = "diamond"
	Tiles        Name = "tiles"
	Expand       Name = "expand"
	Shrink       Name = "shrink"
	ScanDual     Name = "scandual"
	WaveVertical Name = "wavevertical"
	RandomFill   Name = "randomfill"
	Border       Name = "border"
	Matrix       Name = "matrix"
)
